modLoader="javafml"
loaderVersion="[42,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/FantasyFurniture/issues"

[[mods]]
	modId="fantasyfurniture"
	version="${file.jarVersion}"
	displayName="Fantasy's Furniture"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/fantasyfurniture.json"
	displayURL="https://www.apexstudios.dev/fantasys-furniture"
	logoFile="banner.png"
	credits="Apex - Programming, FantasyGaming - Texture Artist"
	authors="Apex, FantasyGaming"
	description="Mod requested by Fantasy which adds varying sets of furniture to your Minecraft world."

[[dependencies.fantasyfurniture]]
	modId="forge"
	mandatory=true
	versionRange="[42.0.2,43.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasyfurniture.custom.mc-publish]
		ignore=true
[[dependencies.fantasyfurniture]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.1,1.20)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasyfurniture.custom.mc-publish]
		ignore=true
[[dependencies.fantasyfurniture]]
	modId="commonality"
	mandatory=true
	versionRange="[3.0.0,4.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasyfurniture.custom.mc-publish]
		ignore=true
[[dependencies.fantasyfurniture]]
	modId="apexcore"
	mandatory=true
	embedded=true
	versionRange="[6.0.0,7.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasyfurniture.custom.mc-publish]
		modrinth="apexcore"
		curseforge="apexcore"
[[dependencies.fantasyfurniture]]
	modId="jei"
	mandatory=false
	versionRange="[11.2.0.241,)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasyfurniture.custom.mc-publish]
		curseforge="jei"
[[dependencies.fantasyfurniture]]
	modId="ctm"
	mandatory=false
	versionRange="*" # ctm versions are funky, just allow all versions
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasyfurniture.custom.mc-publish]
		curseforge="ctm"