modLoader="javafml"
loaderVersion="${forge_version_range}"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexModder/FantasyFurniture/issues"

[[mods]]
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
	updateJSONURL="https://raw.githubusercontent.com/ApexModder/Version/master/fantasyfurniture.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture"
	# logoFile="banner.png"
	# credits=""
	authors="${mod_authors}"
	description=""

[[dependencies.${mod_id}]]
	modId="forge"
	mandatory=true
	versionRange="${forge_version_range}"
	ordering="AFTER"
	side="BOTH"
[[dependencies.${mod_id}]]
	modId="minecraft"
	mandatory=true
	versionRange="${minecraft_version_range}"
	ordering="AFTER"
	side="BOTH"
[[dependencies.${mod_id}]]
    modId="${devworld_mod_id}"
    mandatory=false
    versionRange="${devworld_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="${smoothboot_mod_id}"
    mandatory=false
    versionRange="${smoothboot_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
	modId="${registrator_mod_id}"
	mandatory=true
	versionRange="${registrator_version_range}"
	ordering="AFTER"
	side="BOTH"
[[dependencies.${mod_id}]]
	modId="${apexcore_mod_id}"
	mandatory=true
	versionRange="${apexcore_version_range}"
	ordering="AFTER"
	side="BOTH"
[[dependencies.${mod_id}]]
	modId="${jei_mod_id}"
	mandatory=false
	versionRange="${jei_version_range}"
	ordering="AFTER"
	side="BOTH"
[[dependencies.${mod_id}]]
	modId="${ctm_mod_id}"
	mandatory=false
	versionRange="*" # ctm versions are funky, just allow all versions
	ordering="AFTER"
	side="BOTH"