name: pre_release

on:
  push:
    tags:
      - pv*

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 16 ]

    name: Publish Mod
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read Properties
        uses: christian-draeger/read-properties@1.0.1
        id: mod_version
        with:
          path: ./gradle.properties
          property: mod_version

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}

      - name: Setup Gradle Caching
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: java-${{ matrix.java }}
          gradle-version: wrapper
          save-generated-gradle-jars: true
          save-local-build-cache: true
          save-gradle-dependencies-cache: true
          save-maven-dependencies-cache: true

          gradle-dependencies-cache-key: |
            ~/.gradle/caches/forge_gradle/
            ~/.gradle/caches/parchmentgradle/
            accesstransformer.cfg

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Give Gradle Execute Permissions
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: chmod +x ./gradlew

      - name: Generate Mod Data & Asset Files
        run: ./gradlew data

      - name: Build Mod JARs
        run: ./gradlew build

      - name: Upload Artifacts to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: Mod-Jars
          path: ./build/libs

      - name: Send Version Release Announcement Messages
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_PRE_RELEASE_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_PRE_RELEASE_WEBHOOK_TOKEN }}
          color: '#97C6E7'
          file: './build/libs/fantasyfurniture-1.17.1-${{ steps.mod_version.outputs.value }}.jar'
          message: "Early version of **Fantasy's Furniture** v**_${{ steps.mod_version.outputs.value }}_** (**Minecraft** **_1.17.1_**) is available."

      - name: Stop Gradle Deamons
        run: ./gradlew --stop

      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties