# GitHub Action to auto-magically publish versions
# for tagged commits
name: release

# Run on every push (with version tag)
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-18.04

    steps:
      # Checkout repository & Setup JDK
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8

      # Setup & Restore caches
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ./accesstransformer.cfg
            ./build
          key: ${{ runner.os }}-gradle

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper

      # Validate Gradle Wrapper
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x ./gradlew

      # Generate Minecraft Assets & Data files
      - run: ./gradlew Data # `Data` should match the `runData` gradle task name

      # Build package
      - run: ./gradlew build

      # Upload artifacts to GitHub Actions
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./build/libs

      # Publish mod
      - run: ./gradlew publish
        env:
          APEX_MODS_MAVEN_USERNAME: ${{ secrets.APEX_MODS_MAVEN_USERNAME }}
          APEX_MODS_MAVEN_PASSWORD: ${{ secrets.APEX_MODS_MAVEN_PASSWORD }}

#      - run: ./gradlew curseforge
#        env:
#          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

#      - run: ./gradlew modrinth
#        env:
#          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

      # Kill gradlew deamon (caching requires gradle to not be running)
      - run: ./gradlew --stop

      # Remove problematic files
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties