# GitHub Action to auto-magically publish versions
# for tagged commits
name: release

# Run on every push (with version tag)
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-18.04

    # Required for publishing to GH Packages
    permissions:
      contents: write
      packages: write

    steps:
      # Obtain tag name (version number)
      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      # Setup caching
      - uses: actions/cache@v2
        id: cache-setup
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Checkout repository, Validate Gradle Wrapper & Setup JDK
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
      - run: chmod +x ./gradlew

      # Disable MinecraftForge warning notice
      # - name: Disable MinecraftForge copyright notice
      #   if: steps.cache-setup.outputs.cache-hit != 'true'
      #   run: ./gradlew hideOfficialWarningUntilChanged

      # Generate Minecraft Assets & Data files
      - run: ./gradlew Data # `Data` should match the `runData` gradle task name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build package
      - run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE: ${{ steps.tagName.outputs.tag }}

      # Publish to GitHub Packages
      - run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE: ${{ steps.tagName.outputs.tag }}

      # Publish GH release
      - uses: softprops/action-gh-release@v1
        id: ghRelease
        with:
          body: Auto-Generated GitHub Release - ${{ steps.tagName.outputs.tag }}
          name: ${{ steps.tagName.outputs.tag }}
          files: ./build/libs/*.jar

      # Publish to CurseForge
#      - run: ./gradlew curseforge
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

      # Kill gradlew deamon (caching requires gradle to not be running)
      - run: ./gradlew --stop