name: release

on:
  push:
    tags:
      - v*

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 16 ]

    name: Publish Mod
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Unshallow Repository
        run: git fetch --prune --unshallow

      - name: Read Properties
        uses: christian-draeger/read-properties@1.0.1
        id: mod_version
        with:
          path: ./gradle.properties
          property: mod_version

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}

      - name: Setup Gradle Caching
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: java-${{ matrix.java }}
          gradle-version: wrapper
          save-generated-gradle-jars: true
          save-local-build-cache: true
          save-gradle-dependencies-cache: true
          save-maven-dependencies-cache: true

          gradle-dependencies-cache-key: |
            ~/.gradle/caches/forge_gradle/
            ~/.gradle/caches/parchmentgradle/
            accesstransformer.cfg

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Give Gradle Execute Permissions
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: chmod +x ./gradlew

      - name: Generate Mod Data & Asset Files
        run: ./gradlew data

      - name: Generate Changelog File
        run: ./gradlew gitChangelogTask
        env:
          GENERATE_CHANGELOG: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Mod JARs
        run: ./gradlew build

      - name: Upload Artifacts to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: Mod-Jars
          path: ./build/libs

      - name: Upload Changelog to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: Changelog
          path: ./CHANGELOG.md

      - name: Publish Mod to Maven
        run: ./gradlew publish
        env:
          APEX_MODS_MAVEN_USERNAME: ${{ secrets.APEX_MODS_MAVEN_USERNAME }}
          APEX_MODS_MAVEN_PASSWORD: ${{ secrets.APEX_MODS_MAVEN_PASSWORD }}

      - name: Publish Mod to CurseForge
        run: ./gradlew curseforge
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

      - name: Publish Mod to Modrinth
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

      - name: Send Version Release Announcement Messages
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: '#97C6E7'
          file: ./CHANGELOG.md
          message: "Fantasy's Furniture has been updated to v**_${{ steps.mod_version.outputs.value }}_** for **Minecraft** **_1.17.1_**!"

      - name: Stop Gradle Deamons
        run: ./gradlew --stop

      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties